# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TodoMobile

  target 'TodoMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TodoMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TodoMobile-tvOS

end

pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios'
